name: Deploy

on:
  push:
    branches:
    - dev
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add npm project to $PATH
      run: echo "$GITHUB_WORKSPACE/node_modules/.bin" >> $GITHUB_PATH
    - name: Install NPM deps
      run: npm install
    - name: Build WASM deps
      run: |
        cd crypto
        wasm-pack build
    - name: Publish
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        secrets: |
          DISCORD_TOKEN
          DISCORD_APPID
          DISCORD_PUBKEY
        postCommands: |
          echo "Updating interaction manifests"
          npm run discord-deploy
      env:
        CF_ACCOUNT_ID:  ${{ secrets.CF_ACCOUNT_ID  }}
        DISCORD_TOKEN:  ${{ secrets.DISCORD_TOKEN  }}
        DISCORD_APPID:  ${{ secrets.DISCORD_APPID  }}
        DISCORD_PUBKEY: ${{ secrets.DISCORD_PUBKEY }}
        WASM_PACK_PATH: ${{ join(github.workspace, "/node_modules/.bin/wasm-pack" )}}
        
